contact_links:
  - name: ðŸ“– Documentation
    url: https://nuxtseo.com
    about: Check the documentation for guides and examples.
  - name: ðŸ’¬ Harlan's Discord Server
    url: https://discord.com/invite/5jDAMswWwX
    about: Join the friendly discord server for help with your issue.
